[features]
seeds = false
[programs.devnet]
myepicproject = "3rA998SCfAJofshVLdMpkzwmVi7Xq15uryx8S596C4Bz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/christianpickett/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
